EPOCH_DURATION_IN_DAYS = 14
SPACE_BETWEEN_EPOCHS_IN_SECONDS = 42
CHECK_EPOCH_IN_MINUTES = 15
DEFAULT_EPOCH_APY = 0.05  # APY per epoch in % (aka 0.05 means 5%)
DEFAULT_PORTFOLIO_PERCENTAGE = 0.2  # part of the User.balance which will be staked
GENESIS_EPOCH_ID = 1
